input:
  data_file: ???
  random_seed: 42

train:
  split: train
  model:
    penalty: l2
    solver: liblinear
    C: ${eval:1 / 1e-3}
    random_state: ${input.random_seed}

evaluation:
  split: validation
